src/main/webapp/index.html
=> Implemented description

pom.xml, src/main/java/AppConfig.java, src/main/java/DataKvis.java, src/main/java/KvisService.java
=> Sprød sprød kode

ReactApp/src/Kvis.tsx
Display the real kwestjenBox instead of dummy
=> link to Rasmus' component kwestionBox

.github/workflows/release-pipeline.yml, deploy.sh
=> Refactored pipeline in release to only use 16.x

ReactApp/src/components/login/LoginRecipient.tsx
Signed-off-by: Erlend Tyrmi <erlend@tyrmi.com>
=> fix tokenval deployment

ReactApp/src/components/login/LoginRecipient.tsx
Signed-off-by: Erlend Tyrmi <erlend@tyrmi.com>
=> added deps for react hook (token val: uri in [])

.github/workflows/release-pipeline.yml, deploy.sh
Added domain name as deployment instead of IP.
Should fix problems with geo blocking
=> Deployment

.github/workflows/release-pipeline.yml
Should fix problems with geo blocking
=> Added domain name as deployment instead of IP.

src/main/java/controllers/kvis/KvisAPIController.java, src/main/java/controllers/kvis/dao/KvisDAO.java
Endpoint **/api/kvis/user/{username}** now works and retrieves a list of Kvisses for that user.
=> Endpoint to retrieve Kvisses for a specific user

src/main/java/controllers/Table.java, src/main/java/controllers/kvis/dto/KvisFactory.java, src/main/java/controllers/user/UserAPIController.java, src/main/java/controllers/user/dao/UserDAO.java, src/main/java/controllers/user/dto/UserAPI.java, src/main/java/controllers/user/dto/UserDB.java, src/main/java/controllers/user/dto/UserFactory.java
Endpoint **/api/users** and **/api/users/create** now works so we've the ability to retrieve all users in the DB and create new users.
Payload example:
=> User endpoints GET all POST create

src/main/java/controllers/kvis/KvisAPIController.java, src/main/java/controllers/kvis/dao/KvisDAO.java, src/main/java/controllers/user/UserAPIController.java
- Wrapped all returns from endpoints in both User and Kvis controllers with "Response"
- Created Endpoint for Retrieving a single Kvis from its ID
=> Wrapped everything in appropriate Responses

Dockerfile, pom.xml
I kan lige tage et hurtigt kig, hvis der er interesse for hvordan det er løst :)
=> Dockerfile now handles the build by itself

ReactApp/.env.production
Signed-off-by: erlendtyrmi <s132962@dtu.dk>
=> reinstalled d3

src/main/java/controllers/kvis/dao/KvisDAO.java, src/main/java/controllers/user/dao/UserDAO.java
* KvisDAO error handling updated
* UserDAO updated with better error handling
=> Better error handling en UserDAO and KvisDAO (#82)

Dockerfile, pom.xml, src/main/java/Main.java, src/main/java/controllers/kvis/KvisAPIController.java, src/main/java/controllers/prometheus/Metrics.java, src/main/java/controllers/prometheus/PrometheusAPIController.java
- Created custom Prometheus metrics endpoint
- Slightly more code and labour, but things does actually work with this solution
- Created Metrics.java which is a utility class that holds all the static metrics e.g. Counters, Histograms, etc.
All this is backed up by a Prometheus instance running on the server together with a Grafana instance, so it's possible to both gather the data and visualize it.
Grafana: https://grafana.caprover.kvissen.devops.diplomportal.dk/
- User
- admin
- Password
- Kvissen22
=> Prometheus, Instrumentation and Metrics

ReactApp/src/components/header/DropDownMenu.tsx, ReactApp/src/components/kvisList/KvisListElement.tsx, ReactApp/src/components/login/LoginRecipient.tsx
Knappen play i listen over egne kvisser, starter nu kvis. (TODO: Implementer kvis kode, så man får den rigtige kvis, lige nu er det bare den aktuelle kvis der startes)
Log out knap i menuen, hvis man er logget ind.
Knap, der leder til landing, hvis man er logget ind, hedder "view and edit", og ikke log in.
=> Play your own kvis button

src/main/java/controllers/KvisDatabase.java, src/main/java/controllers/Table.java, src/main/java/controllers/kvis/KvisAPIController.java, src/main/java/controllers/kvis/dao/IResultSetParser.java, src/main/java/controllers/kvis/dao/KvisActivationDAO.java, src/main/java/controllers/kvis/dao/KvisDAO.java, src/main/java/controllers/kvis/dto/kvisAPI/KvisActivateAPIDTO.java, src/main/java/controllers/prometheus/Metrics.java, src/main/java/controllers/prometheus/PrometheusAPIController.java
Endpoints on **/api/kvis/activate** created
- POST
- Body needs to follow structure of KvisActivationAPIDTO.java
- GET **/api/kvis/activate/{findId}**
- Retrieve an activated Kvis
- Return 409 if not present
=> Activate kvis endpoint

ReactApp/.env.development, ReactApp/.env.production, ReactApp/src/components/enterCode/EnterCode.tsx, ReactApp/src/components/kvisList/KvisListElement.test.tsx, ReactApp/src/components/kvisList/KvisListElement.tsx, ReactApp/src/components/playKvis/PlayKvis.tsx, ReactApp/src/data/daos/IKvisDao.ts, ReactApp/src/data/daos/KvisDao.ts, ReactApp/src/data/repositories/IKvisRepository.ts, ReactApp/src/data/repositories/KvisRepository.ts, ReactApp/src/models/KvisActivate.ts, ReactApp/src/stores/KvisStore.ts, ReactApp/src/util/Util.tsx, src/main/java/controllers/kvis/KvisAPIController.java
You can now activate a kvis and play it 
Made some changes to API to allow all users to play without logged in
=> Feature/activate kvis UI

ReactApp/src/components/header/DropDownMenu.tsx, ReactApp/src/components/login/LoginRecipient.tsx, src/main/java/controllers/user/dao/UserDAO.java, src/main/java/services/auth/AuthFilter.java, src/main/java/services/auth/AuthService.java
fix: refactor delay on read token from local storage, until value not null or "null"
result : logout works locally
Signed-off-by: erlendtyrmi <s132962@dtu.dk>
=> fix: read only one user on verify token: Added method to userDAO

src/main/java/controllers/kvis/KvisAPIController.java, src/main/java/controllers/kvis/dao/KvisActivationDAO.java, src/main/java/controllers/prometheus/Metrics.java
- Added new endpoint **api/kvis/deactivate/{kvis_id}**
- Respons with status accepted
- Added metrics
=> Implemented deactivation endpoint and metrics

src/main/java/controllers/Table.java, src/main/java/controllers/kvis/KvisAPIController.java, src/main/java/controllers/kvis/dao/KvisActivationDAO.java, src/main/java/controllers/kvis/dto/kvisAPI/KvisAPIDTO.java, src/main/java/controllers/prometheus/Metrics.java, src/main/java/controllers/result/ResultAPIController.java, src/main/java/controllers/result/dao/KvisResultDAO.java, src/main/java/controllers/result/dto/KvisResultAPIDTO.java, src/main/java/controllers/result/dto/KvisResultFactory.java
Endpoint for getting all the results for a given Kvis.
Endpoint for getting a specific Kvis result. This probably won't be used that much
Endpoint for creating a Kvis result.
=> Kvis Result Endpoints

ReactApp/src/components/login/LoginRecipient.tsx, ReactApp/src/components/playKvis/PlayKvis.tsx
Signed-off-by: erlendtyrmi <s132962@dtu.dk>
=> Moved getActivatedKvis to after login

src/main/java/controllers/kvis/KvisAPIController.java, src/main/java/controllers/kvis/dao/KvisDAO.java, src/main/java/controllers/prometheus/Metrics.java
Created endpoint **api/kvis/delete/{id}** where ID is the unique ID of the Kvis. If everything goes well, then the endpoint returns 204 No Content :+1:
=> Delete kvis endpoint

src/main/java/services/auth/AuthFilter.java, src/main/java/services/auth/repo/remoteAuth/TicketValidator.java
Signed-off-by: erlendtyrmi <s132962@dtu.dk>
=> logs removed
